---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - issues
  - contact
  - default
  - home
  - list
  - tiles-list
  - 2-lists
- type: directory
  path: sections
  label: Sections
  create: documents
  match: "**/*"
  templates:
  - section
- type: document
  path: _data/nav.json
  label: Nav
- type: document
  path: _data/langs.json
  label: Lang
- type: document
  path: _data/settings.json
  label: Settings
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start
