---
label: Default
hide_body: true
fields:
- type: text
  name: title
  label: Title
  default: ''
- type: text
  name: description
  label: Description
  default: ''
- type: text
  name: lang
  label: Lang
  default: en
- type: textarea
  name: text
  label: Text
  default: ''
  config:
    wysiwyg: true
    schema:
      format: html-blocks
- type: boolean
  name: show_widget
  label: Show Widgets
  default: ''
- type: file
  name: image
  label: Illustration
  default: ''
- type: textarea
  name: text
  label: Text
  default: "<h2>Use Silex in your project</h2>"
  config:
    wysiwyg: true
    schema:
      format: html-blocks
- type: textarea
  name: cta-link
  label: CTA Link
  default: "<b>Documentation</b>"
  config:
    wysiwyg: true
    schema:
      format: html-blocks
- type: textarea
  name: cta-primary
  label: CTA Primary
  default: "<b>Download</b>"
  config:
    wysiwyg: true
    schema:
      format: html-blocks
- name: permalink
  type: text
  label: Permalink
  config:
    required: true
- name: layout
  type: text
  hidden: true
  label: layout
  default: default
  config:
    required: true
