---
id: default
label: Default
fields:
  - type: text
    name: title
    label: Title
    default: ''
  - type: text
    name: description
    label: Description
    default: ''
  - type: text
    name: lang
    label: Lang
    default: en
  - name: permalink
    type: text
    label: Permalink
    config:
      required: true
  - name: layout
    type: text
    hidden: true
    label: layout
    default: default
    config:
      required: true
name: default.yml
hide_body: true
